# Generated by Django 2.2.10 on 2020-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_phase_number', models.CharField(max_length=30)),
                ('research_phases30', models.CharField(max_length=30)),
                ('research_phases7', models.CharField(max_length=30)),
            ],
        ),
    ]
