# Generated by Django 2.2.10 on 2020-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0002_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creators_title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Startdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsAndInnovations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name (blue ones were added during last update)', max_length=30)),
                ('url', models.CharField(help_text='clickable link', max_length=30)),
                ('web_launchyear', models.IntegerField(help_text='year of weblaunch / introduction / founding')),
                ('prime_phase_alpha', models.CharField(help_text='primary phase of workflow targeted', max_length=30)),
                ('prime_phase_number', models.IntegerField(help_text='phase order')),
                ('function_free', models.TextField(help_text='what is/does it? (free text)', max_length=1000)),
                ('ui_functionfree', models.CharField(help_text='user input for what is/does it?', max_length=30)),
                ('function_controlled', models.CharField(help_text='what is/does it? (controlled)', max_length=30)),
                ('geo_category', models.CharField(help_text='open / efficient / good', max_length=30)),
                ('ui_geo_category', models.CharField(help_text='Does the tool make science more open, efficient or good / reproducible?', max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('twitter_follow_latest', models.IntegerField(help_text='Twitter followers')),
                ('active_pre', models.CharField(help_text='preparation / define research priorities / get funding', max_length=30)),
                ('active_dis', models.CharField(help_text='discovery, data collection', max_length=30)),
                ('active_ana', models.CharField(help_text='analysis', max_length=30)),
                ('active_wri', models.CharField(help_text='authoring / writing / including annotations', max_length=30)),
                ('active_pub', models.CharField(help_text='publication / archiving / sharing', max_length=30)),
                ('active_out', models.CharField(help_text='outreach & visibility', max_length=30)),
                ('active_ass', models.CharField(help_text='assessment / metrics (incl. comments, discussion)', max_length=30)),
            ],
        ),
    ]
