# Generated by Django 2.2.10 on 2020-04-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0003_recommendations_startdata_toolsandinnovations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
