# Generated by Django 2.2.10 on 2020-04-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0004_auto_20200419_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Recomm',
        ),
    ]
