# Generated by Django 2.2.10 on 2020-04-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0005_auto_20200419_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomm',
            new_name='Recommendation',
        ),
    ]
