# Generated by Django 2.2.10 on 2020-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0006_auto_20200419_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsandinnovations',
            name='prime_phase_number',
            field=models.CharField(default='', help_text='phase order', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolsandinnovations',
            name='twitter_follow_latest',
            field=models.CharField(help_text='Twitter followers', max_length=30),
        ),
        migrations.AlterField(
            model_name='toolsandinnovations',
            name='web_launchyear',
            field=models.CharField(default='', help_text='year of weblaunch / introduction / founding', max_length=30),
        ),
    ]
